# Generated by Django 5.0.4 on 2024-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.IntegerField(default=0),
        ),
    ]
