# Generated by Django 5.0.4 on 2024-04-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_user_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=20)),
                ("activity_start_date", models.DateField()),
                ("activity_end_date", models.DateField()),
                ("activity_duration", models.DurationField()),
                ("activity_resource", models.ManyToManyField(to="app1.user")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=50)),
                (
                    "project_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.activity"
                    ),
                ),
            ],
        ),
    ]
