# Generated by Django 5.0.4 on 2024-05-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_activity_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_activity",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="Project Name", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "control",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_groups",
                        to="app1.user",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="members", to="app1.user"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="group",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="app1.group",
            ),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("source", models.CharField(max_length=100)),
                ("target", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("lag", models.IntegerField(blank=True, default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="app1.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("text", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("progress", models.FloatField()),
                ("parent", models.CharField(max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="app1.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WBSElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.wbselement",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
