# Generated by Django 5.0.4 on 2024-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_wbselement'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_progress',
            field=models.IntegerField(default=0),
        ),
    ]
